pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    node_latest:
      node_version: '>=13.0.0'
    node_12_x:
      node_version: 12.x
    node_10_x:
      node_version: 10.x

steps:
  - checkout: self
    fetchDepth: 1
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version) 
  - script: |
      npm install -g codecov eslint
      npm install -d
    displayName: Install dependencies
  - script: |
      eslint .
    displayName: Lint
    condition: always()
  - script: |
      npm run cov
    displayName: Test
    condition: always()
  - script: |
      nyc report --reporter=text-lcov > coverage.lcov
      codecov
    displayName: Report to codecov.io
